### ISSUE TITLE
Vue/Buefy mailgo doesn't work in production.

### ISSUE THREAD

**Issue by helloalexdodd** [manzinello/mailgo#89] opened 2020-10-18 22:01 UTC
Mailgo is working as it should in development mode but when I test in production, rather than open the mailgo window it attempts to redirect the url to `.../#/mailgo`. I have tried the different configurations in the docs but with no luck. Below is my dependencies as well as my implementation. I am using netlify for hosting, as well as Vue and Buefy.

package.json
```json
"dependencies": {
    "@mdi/font": "^5.5.55",
    "axios": "^0.20.0",
    "buefy": "^0.9.3",
    "core-js": "^3.6.5",
    "mailgo": "^0.9.17",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^6.2.2",
    "lint-staged": "^9.5.0",
    "vue-template-compiler": "^2.6.11"
  },
```
main.js
```js
import Vue from 'vue';
import Buefy from 'buefy';
import axios from 'axios';
import router from '@/router';
import store from '@/store';
import '@/store/subscriber';
import 'buefy/dist/buefy.css';
import '@mdi/font/css/materialdesignicons.css';
import 'mailgo/dist/mailgo.min';
import titleMixin from '@/mixins/titleMixin';
import App from './App.vue';

Vue.config.productionTip = false;

Vue.mixin(titleMixin);
Vue.use(Buefy);

Vue.prototype.$http = axios;
const token = localStorage.getItem('x-auth-token');
if (token) Vue.prototype.$http.defaults.headers.common['x-auth-token'] = token;
// Vue.prototype.$http.defaults.baseURL = 'http://localhost:5000/v1/';
Vue.prototype.$http.defaults.baseURL = 'https://full-stack-expense-tracker.herokuapp.com/v1/';

new Vue({
  router,
  store,
  strict: process.env.NODE_ENV !== 'production',
  render: (h) => h(App),
}).$mount('#app');

```
implementation
```html
<template>
  <div>
    <b-button type="is-text" class="my-3 mx-3" @click="open = true">
      <b-icon icon="menu" size="is-medium" />
    </b-button>
    <b-sidebar
      v-model="open"
      type="is-light"
      :fullheight="fullheight"
      :fullwidth="fullwidth"
      :overlay="overlay"
      :right="right"
      :can-cancel="canCancel"
    >
      <div class="section">
        <b-menu>
          <b-menu-list>
            <li class="buttons is-centered mb-6">
              <template v-if="authenticated">
                <a href="#" class="button is-link has-text-weight-bold" @click="logOut">Log Out</a>
              </template>
              <template v-else>
                <router-link :to="'/signup'" class="button is-success has-text-weight-bold"> Sign up </router-link>
                <router-link :to="'/login'" class="button is-link has-text-weight-bold"> Log In </router-link>
              </template>
            </li>
            <p class="mb-4">Having an issue or have a suggestion?</p>
            <b-menu-item
              icon="email"
              label="Get In Touch"
              href="#mailgo"
              data-address="hello"
              data-domain="alexdodd.ca"
              data-subject="Hello! 🦖✨😃"
            />
            <b-menu-item
              icon="ladybug"
              label="Report a bug"
              href="https://github.com/helloalexdodd/full-stack-expense-tracker/issues/new"
              target="_blank"
              rel="noopener noreferrer"
            />
          </b-menu-list>
        </b-menu>
      </div>
    </b-sidebar>
  </div>
</template>
```
```js
<script>
import { mapGetters, mapActions } from 'vuex';

export default {
  name: 'Sidebar',
  data() {
    return {
      open: false,
      overlay: false,
      fullheight: true,
      fullwidth: false,
      right: false,
      canCancel: ['escape', 'outside'],
    };
  },
  computed: {
    ...mapGetters({
      authenticated: 'auth/authenticated',
    }),
  },
  methods: {
    ...mapActions({
      signOut: 'auth/signOut',
    }),
    async logOut() {
      await this.signOut();
      this.$router.push('/login');
    },
  },
};
</script>
```

**Comment by manzinello** [comment] 2020-10-19 06:45
Thank you so much for your bug reporting. Unfortunately, I don't know Vue and in fact in the Docs there is still a `// TODO` (https://mailgo.dev/docs/frameworks#vue), but I will try very soon to reproduce an installation with Vue and Buefy and return back here with some details, maybe I will create an example site with mailgo (like what I have already done with Gatsby).

Just a question: have you ever tried to import `mailgo` and then  call `mailgo()`? You have used this type of installation (https://mailgo.dev/docs/frameworks#first-way-no-configuration), but have you tried this one (https://mailgo.dev/docs/frameworks#second-way-with-configuration)? Just to have more details to understand in deep what is happening here and try to solve. Thank you.

**Comment by helloalexdodd** [comment] 2020-10-19 13:14
Hey that worked! You end up having to do it in App.vue rather than main.js, but that totally works. If you like I'd be happy to create and take on the task of updating the docs for Vue.

**Comment by manzinello** [comment] 2020-10-19 13:19
Hi Alex, I was working on a completely new repository for Vue just for this issue! I'm happy you have solved, here you can find my basic implementation https://github.com/manzinello/vue-mailgo and here the same repository deployed https://vue-mailgo.netlify.app/. Well, I have worked in `main.js`, you have find another solution? I don't know Vue, if you want to update the docs of mailgo.dev you are completely free to submit a PR directly here https://github.com/manzinello/mailgo.dev/blob/master/docs/frameworks.md.

If the problem is solved can I close this issue maybe? Thank you so much.

**Closed as completed** 2020-10-19 15:52 UTC
