### ISSUE TITLE
FIX z-index on Safari

### ISSUE THREAD

**Issue by manzinello** [manzinello/mailgo#16] opened 2019-05-11 12:37 UTC
On Safari the modal in some cases goes under the background!

**Comment by millette** [comment] 2019-05-11 17:11
Dupe of #3 ?

**Comment by manzinello** [comment] 2019-05-11 17:20
They are a bit different, this issue is about also mailgo.js.org, the #3 has appeared on a website with particular z-index in its CSS. However, I am working on a new version of mailgo (0.3.0) that will change a bit its working (in particular with a really better init, it is the issue #8), I think that I will release it in a few days. The HTML structure will remain the same, so then I will work on these two (similar) issues, that are completely a CSS problem. Do you want to help me in this point? Have tested mailgo? What do you think about?

**Closed as completed** 2019-05-11 22:36 UTC
Labels: bug
